FROM golang:1.20 AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build not_escape.go print_memory.go
FROM alpine:3.17
WORKDIR /app
COPY --from=builder /app/not_escape /app/
EXPOSE 8081
ENV GODEBUG="gctrace=1"
CMD ["/app/not_escape"]
