FROM golang:1.20 AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build heap_alloc.go print_memory.go
FROM alpine:3.17
WORKDIR /app
COPY --from=builder /app/heap_alloc /app/
EXPOSE 8081
ENV GODEBUG="gctrace=1"
CMD ["/app/heap_alloc"]
